{% set name = "eliot" %}
{% set version = "1.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c2f099a3e8d5ecfc22745766e7cc664a48db64b6b89d986dff270491d8683149

build:
  number: 1
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six
    - boltons
    - pyrsistent
    - zope.interface
    - aiocontextvars  # [py<37]

test:
  imports:
    - eliot

about:
  home: http://github.com/itamarst/eliot
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Action-tracing logging for Python: the logging library that tells you why it happened'
  description: |
    Most logging systems tell you what happened in your application, whereas eliot also tells you why it happened. eliot is a Python logging system that outputs causal chains of actions: actions can spawn other actions, and eventually they either succeed or fail. The resulting logs tell you the story of what your software did: what happened, and what caused it.
  doc_url: http://eliot.readthedocs.io/
  dev_url: https://github.com/itamarst/eliot

extra:
  recipe-maintainers:
    - itamarst
