travis:
  secure:
    BINSTAR_TOKEN: iZbEQd10Xp7OWwfKiacBLEgNpV6iAhslNiIK4Ah0HeHIg8NjhTafLJ5lhBT9aPDTSr4dgoeY09ejBxVYPMczmgVyyXpLU/Ghq9n/XuhUq65DTAPCjUDJGf2pGlmWuEX9F9Y+ueibqT/opemW8bs/KLoIs6Yb569iQ03IqikK+MThsgHCxi8osamLI+G+/C05iQJrRV69ZZRyIdhBEWKn+0EHWKzP4ZWjVSlNgCiwIx88DqT69Z4nHQDLx/CVovdak+zRZzbPoNsPEEU6IIBR2+iMzehPJ7cm3vBN/LLmY/+o5JvP/HXaKPocme+zOKYdnBonyRLvumLioXjqyWFy5Ct7YDXUR4eQdKQSJOiimy2yplPISzRaLiOSA+uqjV2jUJsuHr/9K7fr5RQ2hzYVRsQINPsVoBLyamEzUbNbZ2HizfpTXin4Mrr1iLpv4w8l1PuDCOmGjQJTWtDFYl+quDP5vMuUH04pLri4Bp7B/3l/gbb/prW80nbxi8LjDAfvo0BiY6Q9C9T3D1smOZfq7yhTWbm1wobcRhUvY6lj9jvICqnuOEeOOfgYezWjM+m3lu6gyhdmJYCHpcKpYnk7+2zrIBCpg77aA7ui9da27rzkycgYfRtBnkLRKEesJJhFPb2WlbX3S+ENNouWrnxNJafGMk+0CevwuqPtHw7HdKg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
