travis:
  secure:
    BINSTAR_TOKEN: JBHxNdtEzvI69d6nZTyD44DMecESsWafvRa6XQdxB7ve854SCh0ISydzvH+XU6BT/mw4tMfv1oVqOkPz2hjdmC2lV5fVOv0ZpwEnJPWyNXn5986N2+aTIH/JHKP+epTveAIEilUnXOHPGdXnpoQAhBhdhghoM6k6Egms/kaH1e623DAA8xADoPzEBHDGZ0BbCNJMQquu1vrMyK4MLn55GEO36sDl2z81c/deGH8l2KvuOotSFk7oKNgrpyG6+FNCCo7yqhYq8wYIWOOJLSL6kT7xfcFuuYDXUSeduPjQMWuD3qwVODWG0H8pxDowmsqR/Hfv0ux5k+JNsq+uaGkyPEjS7iUiYZtYNWHs7+Ign+R41AMHWf+O/Ijv2ZVWXTYKXRguWeIbBC9dY9Zo/EG1PvuWOwQkAKSW1pArU0bnmdU5fQVN+1kqsZPkZ/f6T21wcLfTp5RhBspzo0NR6Rje8IQ18FPCtXZaVD/lKFxsU+tCvDJGfzlwKdLu82erfZ9dbDwjJt09QccW3+Ac1iv1o0femRevP9x1rpmy3CMmaWJikSxKwAt32VMvK/C807GJ06p/v9fOuTCQtIHSHzIxwuOHxOfg+dxT0/2fj/YOw0LVwfCPWdheMeU82THe+AXzcIkqBkyVtfwZ7a+CFWnjAC56qnpBkmswcAWtMjD25os=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
